# Generated by Django 4.2.5 on 2023-09-30 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name_plural': 'User settings'},
        ),
    ]
