# Generated by Django 4.2.5 on 2023-09-18 02:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('configfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3d508275-5b39-4363-8f91-6997092f3eaf'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5281eb87-205a-4b1c-b3cc-6727ddf45c35'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8ad9fc16-f417-4277-848f-2623b9d03d01'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
