# Generated by Django 4.2.5 on 2023-09-28 16:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('configfiles', '0002_alter_configfile_id_alter_file_id_alter_location_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configfiles.location'),
        ),
        migrations.AlterField(
            model_name='configfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c4a1dbd7-20cc-4ffd-ad4a-151dcf3714f9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ebbf63d5-63e8-4c09-890f-10e4edb09bd7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dec329ff-59d1-4bec-9efd-f5ba7fb76b5e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
