# Generated by Django 4.2.5 on 2023-09-30 16:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('configfiles', '0004_configfile_api_key_alter_configfile_id_alter_file_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ea452d55-8495-4f15-b878-72a64c19ff03'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.UUID('50373716-54c1-4727-9017-5b908c02a930'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
