# Generated by Django 4.2.5 on 2023-09-30 16:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('configfiles', '0005_alter_configfile_id_alter_file_id_alter_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configfile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
