# Generated by Django 4.2.5 on 2023-09-30 17:28

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('configfiles', '0007_alter_location_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
    ]
