# Generated by Django 4.2.5 on 2023-09-28 16:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apikeys', '0002_alter_apikey_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7753e3ad-ced1-4414-82c8-6246c0f2c732'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
