# Generated by Django 4.2.5 on 2023-09-30 16:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apikeys', '0003_alter_apikey_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='id',
            field=models.UUIDField(default=uuid.UUID('02b4ce5a-be8c-4b49-9b4f-598105cace08'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
